# ### Registrierung testen
# POST http://localhost:3000/register
# Content-Type: application/json

# {
#   "username": "testuser",
#   "email": "test@example.com",
#   "password": "SicheresPasswort123!"
# }

# ### Login testen
# POST http://localhost:3000/login
# Content-Type: application/json

# {
#   "username": "testuser",
#   "password": "SicheresPasswort123!"
# }

### Register Grizabella
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Grizabella",
  "email": "griz@cats.com",
  "password": "Jellicle1981"
}

### Login Grizabella
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Grizabella",
  "password": "Jellicle1981"
}

### Login OldDeuteronomy
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "OldDeuteronomy",
  "password": "Jellicle1981"
}

###

### Login RumTumTugger
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "RumTumTugger",
  "password": "Jellicle1981"
}

### Login OldDeuteronomy
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "OldDeuteronomy",
  "password": "Jellicle1981"
}

###

### Register Ji-Yong
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Ji-Yong",
  "email": "jiyong@example.com",
  "password": "Jellicle1981"
}

### Login Ji-Yong
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Ji-Yong",
  "password": "Jellicle1981"
}